[package]
name = "tokenizers2c"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]

[dependencies]
libc = "0.2.142"
tokenizers = {version = "0.13.3", default-features = false, features = ["unstable_wasm"]}

[profile.release]
strip = true
lto = true
